App/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app'

urlpatterns = [
    path('', views.Dashboard.as_view(), name='dashboard'),
    path('login/', views.LoginForm.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('signup/', views.SignUpForm.as_view(), name='signup'),
    path('update/<int:pk>', views.UpdateData.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteData.as_view(), name='delete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Assignment/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App.urls'))
]

App/models.py
from django.db import models


# Create your models here.
class Data(models.Model):
    file = models.FileField(upload_to='file/')
    desc = models.CharField(max_length=300)

    def __str__(self):
        return self.desc[:20]

App/forms.py
from django import forms
from .models import Data


class DataForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = '__all__'

App/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import TemplateView
from django.views.generic import FormView, RedirectView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse, reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout, login
from django.contrib.auth.forms import UserCreationForm
from .forms import DataForm
from .models import Data


# Create your views here.
@method_decorator(login_required(login_url=reverse_lazy('app:login'), redirect_field_name=''), name='dispatch')
class Dashboard(TemplateView):
    template_name = 'app/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(Dashboard, self).get_context_data(**kwargs)
        context['form'] = DataForm()
        context['data'] = Data.objects.all()
        return context

    def post(self, request):
        if request.method == 'POST':
            form = DataForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse_lazy('app:dashboard'))
            return HttpResponseRedirect(reverse_lazy('app:dashboard'))


class LoginForm(FormView):
    template_name = 'app/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('app:dashboard')

    def form_valid(self, form):
        login(self.request, form.get_user())
        return HttpResponseRedirect(reverse_lazy('app:dashboard'))


class Logout(RedirectView):
    def get(self, request, *args, **kwargs):
        logout(self.request)
        return HttpResponseRedirect(reverse_lazy('app:login'))


class SignUpForm(FormView):
    template_name = 'app/signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('app:login')

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('app:login'))
        return HttpResponseRedirect(reverse_lazy('app:signup'))


class UpdateData(UpdateView):
    template_name = 'app/update.html'
    form_class = DataForm
    success_url = reverse_lazy('app:dashboard')
    model = Data


class DeleteData(DeleteView):
    template_name = 'app/delete.html'
    success_url = reverse_lazy('app:dashboard')
    model = Data

App/templates/app/dashboard.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-3 row">
        <h1 class="text-primary">Welcome <b class="text-danger">{{ request.user|title }}</b></h1>
        <div class="col-4">
            <h1 class="text-white bg-secondary text-center p-1">Add New Data</h1>
            <form class="form-control" method="post" enctype="multipart/form-data">
                {{ form|crispy }}
                {% csrf_token %}
                <input type="submit" value="Add File" class="btn btn-success">
            </form>
        </div>
        <div class="col-8">
            <h1 class="text-white bg-secondary text-center p-1">Data</h1>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">File</th>
                    <th scope="col">Desc</th>
                    <th scope="col" colspan="2">Action</th>
                </tr>
                </thead>
                <tbody>
                {% if data %}
                    {% for d in data %}
                        <tr>
                            <td>{{ d.id }}</td>
                            <td><a href="media/{{ d.file }}" class="text-decoration-none">File</a></td>
                            <td>{{ d.desc }}</td>
                        <td><a  class="btn btn-success" href="{% url 'app:update' d.id %}">Edit </a></td>
                        <td><a  class="btn btn-danger" href="{% url 'app:delete' d.id %}">Delete </a></td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <td colspan="3">No Data is Found</td>
                {% endif %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

App/templates/app/delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-3">
        <h1 class="text-center bg-secondary text-white">Delete Data......</h1>
        <form method="post">
            {% csrf_token %}
            <p>Are you sure Delete the Data "{{ object }}" from the Database ............</p>
            {{ form }}
            <input type="submit" value="Confirm" class="btn btn-danger">
        </form>
    </div>
{% endblock %}

App/templates/app/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-3 row">
    <div class="col-3"></div>
    <div class="col-6">
        <form method="post" class="form-control">
        <h1 class="bg-secondary text-white p-2 text-center">Login</h1>
            {{ form|crispy }}
            {% csrf_token %}
            <input type="submit" value="Login" class="btn btn-success">
            <a class="btn btn-success me-3 float-end" href="{% url 'app:signup' %}">Sign Up</a>
        </form>
    </div>
    </div>
{% endblock %}

App/templates/app/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-3 row">
    <div class="col-3"></div>
    <div class="col-6">
        <form method="post" class="form-control">
        <h1 class="bg-secondary text-white p-2 text-center">Login</h1>
            {{ form|crispy }}
            {% csrf_token %}
            <input type="submit" value="Signup" class="btn btn-success">
            <a class="btn btn-success me-3 float-end" href="{% url 'app:login' %}">Login</a>
        </form>
    </div>
    </div>
{% endblock %}

App/templates/app/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row mt-3">
        <div class="col-3"></div>
        <div class="col-6">
            <h1 class="text-white bg-secondary text-center p-1">Update Data</h1>
            <form class="form-control" method="post" enctype="multipart/form-data">
                {{ form|crispy }}
                {% csrf_token %}
                <input type="submit" value="Update File" class="btn btn-success">
            </form>
        </div>
    </div>

{% endblock %}

App/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Assignment</title>
    <!-- Bootstrap CSS -->
    <link href="{% static 'Bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'Bootstrap/css/style.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'app:dashboard' %}">Sakib Assignment</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'app:dashboard' %}">Dashboard</a>
                    </li>
                </ul>
            </div>
            <div class="d-flex">
                {% if request.user.is_authenticated %}
                    <a class="btn btn-danger" href="{% url 'app:logout' %}">Logout</a>
                {% else %}
                    <a class="btn btn-danger" href="{% url 'app:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="{% static 'Bootstrap/js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'Bootstrap/jquery/jquery-3.6.0.js' %}"></script>
</html>